### ISSUE TITLE
Rolling not working

### ISSUE THREAD

**Issue by tanhoang181** [zhxnlai/ZLSinusWaveView#2]
Hi,

Your library is good but I can't use rolling mode.
When I choose "Rolling", I see nothing's changed. Is it working?

Thanks.

**Comment by zhxnlai** [comment]
That is right. This view does not support rolling mode. Here is one that does: https://github.com/zhxnlai/ZLHistogramAudioPlot

**Comment by tanhoang181** [comment]
Thank you so much. It works :)
